name: "Check Minecraft Paper server versions"

on:
  push:
    branches:
      - feature/update-workflows
  schedule:
    - cron: "0 8 * * *" # Run every day in the morning

jobs:
  check-new-paper-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch current versions
        run: |
          curl -X 'GET' 'https://api.papermc.io/v2/projects/paper' -H 'accept: application/json' | jq -r '.versions[]' > current_versions.txt

      - name: Compare versions and find new ones
        run: |
          new_versions=""
          for version in $(cat current_versions.txt); do
            if [ ! -d "$version" ]; then
              new_versions="$new_versions $version"
            fi
          done
          echo "Found new versions: $new_versions"
          echo "new_versions=$new_versions" >> $GITHUB_ENV

      - name: Trigger generate-server-configs job
        if: env.new_versions != ''
        uses: actions/github-script@v6
        with:
          script: |
            new_versions = process.env.new_versions.split(/\s+/)
            for (const version of new_versions) {
              console.log(`Triggering generate-server-configs job for version ${version}`)
              github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'extract-configs-server.yml',
                ref: context.ref,
                inputs: {
                  paper_version: version
                }
              })
            }
